# Use a base image with Java and the desired version
FROM adoptopenjdk:11-jdk-hotspot

# Copy the JAR file generated by the Spring Boot build into the container
ADD target/newsletter-subscription-docker.jar newsletter-subscription-docker.jar

# Expose the port that your Spring Boot application listens on
EXPOSE 8080

# Define the command to run your Spring Boot application when the container starts
CMD ["java", "-jar", "newsletter-subscription-docker.jar"]
